# Generated by Django 3.0.8 on 2020-07-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descripton',
            new_name='description',
        ),
    ]
